[build]
  command = "npm run build"
  publish = "build/"
  functions = "netlify/functions/"

# Apply a 30-second timeout to all functions using a wildcard.
# This is a more robust way to set a global timeout.
[functions."*"]
  timeout = 30

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
