[build]
  command = "npm run build"
  publish = "build/"
  functions = "netlify/functions/"

[functions]
  timeout = 30

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
